from __future__ import annotations

from typing import Any


CAPABILITY_REGISTRY: list[dict[str, Any]] = [
    {
        "capability_id": "baseline_fe",
        "label": "基准固定效应回归",
        "estimator": "reghdfe",
        "required_roles": ["depvar", "core_var"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["fixed_effects", "cluster"],
        "default_focus_term_rule": "core_var",
        "package_requirements": ["reghdfe"],
        "builder": "standard_model",
    },
    {
        "capability_id": "iv_fe",
        "label": "工具变量固定效应回归",
        "estimator": "ivreghdfe",
        "required_roles": ["depvar", "endogenous", "instruments"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["fixed_effects", "cluster", "iv"],
        "default_focus_term_rule": "endogenous",
        "package_requirements": ["ivreghdfe", "reghdfe"],
        "builder": "standard_model",
    },
    {
        "capability_id": "ppml_fe",
        "label": "PPML 固定效应回归",
        "estimator": "ppmlhdfe",
        "required_roles": ["depvar", "core_var"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["fixed_effects", "cluster"],
        "default_focus_term_rule": "core_var",
        "package_requirements": ["ppmlhdfe", "reghdfe"],
        "builder": "standard_model",
    },
    {
        "capability_id": "did_twfe",
        "label": "TWFE DID",
        "estimator": "reghdfe",
        "required_roles": ["depvar", "treatment"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["fixed_effects", "cluster", "did"],
        "default_focus_term_rule": "treatment",
        "package_requirements": ["reghdfe"],
        "builder": "standard_model",
    },
    {
        "capability_id": "did_csdid",
        "label": "CSDID",
        "estimator": "csdid",
        "required_roles": ["depvar", "id", "time", "gvar"],
        "optional_roles": ["controls"],
        "supports": ["did", "staggered_treatment", "figure_output"],
        "default_focus_term_rule": "ATT",
        "package_requirements": ["csdid", "drdid"],
        "builder": "standard_model",
    },
    {
        "capability_id": "did_csdid_event",
        "label": "CSDID 事件研究图",
        "estimator": "csdid",
        "required_roles": ["depvar", "id", "time", "gvar"],
        "optional_roles": ["controls", "cluster"],
        "supports": ["did", "staggered_treatment", "figure_output", "event_study"],
        "default_focus_term_rule": "csdid_event_terms",
        "package_requirements": ["csdid", "drdid"],
        "builder": "standard_model",
    },
    {
        "capability_id": "parallel_trends",
        "label": "平行趋势",
        "estimator": "reghdfe",
        "required_roles": ["depvar", "gvar"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["event_study", "figure_output"],
        "default_focus_term_rule": "event_study_terms",
        "package_requirements": ["reghdfe"],
        "builder": "parallel_trends",
    },
    {
        "capability_id": "psm_did",
        "label": "PSM-DID",
        "estimator": "reghdfe",
        "required_roles": ["depvar", "treatment"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["matching", "did"],
        "default_focus_term_rule": "treatment",
        "package_requirements": ["psmatch2", "reghdfe"],
        "builder": "psm_did",
    },
    {
        "capability_id": "placebo",
        "label": "安慰剂检验",
        "estimator": "reghdfe",
        "required_roles": ["depvar", "treatment", "gvar"],
        "optional_roles": ["controls", "id", "time", "cluster"],
        "supports": ["placebo", "did"],
        "default_focus_term_rule": "treatment",
        "package_requirements": ["reghdfe"],
        "builder": "placebo",
    },
    {
        "capability_id": "panel_tobit",
        "label": "面板 Tobit",
        "estimator": "xttobit",
        "required_roles": ["depvar", "core_var", "id", "time"],
        "optional_roles": ["controls", "cluster"],
        "supports": ["panel_xtset", "factor_time"],
        "default_focus_term_rule": "core_var",
        "package_requirements": [],
        "builder": "standard_model",
    },
    {
        "capability_id": "panel_nb_fe",
        "label": "面板负二项固定效应",
        "estimator": "xtnbreg",
        "required_roles": ["depvar", "core_var", "id", "time"],
        "optional_roles": ["controls", "cluster"],
        "supports": ["panel_xtset", "factor_time", "fe_option"],
        "default_focus_term_rule": "core_var",
        "package_requirements": [],
        "builder": "standard_model",
    },
    {
        "capability_id": "robustness_bundle",
        "label": "稳健性检验组",
        "estimator": "bundle",
        "required_roles": ["depvar"],
        "optional_roles": ["core_var", "controls", "id", "time", "cluster"],
        "supports": ["bundle", "multi_model"],
        "default_focus_term_rule": "inherit",
        "package_requirements": [],
        "builder": "bundle",
    },
    {
        "capability_id": "heterogeneity_bundle",
        "label": "异质性检验组",
        "estimator": "bundle",
        "required_roles": ["depvar"],
        "optional_roles": ["core_var", "controls", "id", "time", "cluster", "group_var"],
        "supports": ["bundle", "subgroup"],
        "default_focus_term_rule": "inherit",
        "package_requirements": [],
        "builder": "bundle",
    },
]


def capability_map() -> dict[str, dict[str, Any]]:
    return {item["capability_id"]: item for item in CAPABILITY_REGISTRY}
